Add reviews
theIvanChornyi/html-css-project pull request #15
Opened 2022-08-06 08:24 UTC by Kate3587

2022-08-06 18:33 UTC, theIvanChornyi requested changes

2022-08-06 18:33 UTC, theIvanChornyi commented on src/partials/customer-reviews.html
> +    <div class="container customer__container">
container Это отдельная секция, обёртку customer__container, вложи во внутрь

2022-08-06 18:33 UTC, theIvanChornyi commented on src/partials/customer-reviews.html
> +            <div class="customer__wrapperswiper-slide">
Вместо дива используй тег article мне кажется это именно он

2022-08-06 18:33 UTC, theIvanChornyi commented on src/partials/customer-reviews.html
> +                <img class="customer__img" src="./images/hero1-desk.png" alt="customer review number 1">
Картинку оберни в div. назови его например customer__thumb, и задай ему в стилях необходимый размер, border radius 50%, overflow hidden, так ты сделаешь картинку круглой, внутри вложи картинку но уже не пнг а jpg они весят меньше.

2022-08-07 01:58 UTC, Kate3587 commented on src/partials/customer-reviews.html
> +                <img class="customer__img" src="./images/hero1-desk.png" alt="customer review number 1">
это не та картинка

2022-08-07 06:43 UTC, theIvanChornyi requested changes

2022-08-07 06:43 UTC, theIvanChornyi commented on src/partials/customer-reviews.html
> +    <div class="swiper mySwiper">
Внутри контейнера добавь невидимый заголовок h2,  и дай ему класс visually-hidden, так как это секция и ей нужен заголовок.

2022-08-07 06:43 UTC, theIvanChornyi commented on src/partials/customer-reviews.html
> +                <div>
Поменяй div без класса на артикль, чтобы читалка понимала что это она видит перед собой

2022-08-07 06:43 UTC, theIvanChornyi commented on src/partials/customer-reviews.html
> +                <div>
Поменяй div без класса на артикль, чтобы читалка понимала что это она видит перед собой

2022-08-07 06:43 UTC, theIvanChornyi commented on src/partials/customer-reviews.html
> +                <div>
Поменяй div без класса на артикль, чтобы читалка понимала что это она видит перед собой

2022-08-07 06:43 UTC, theIvanChornyi commented on src/partials/customer-reviews.html
> +                    <p class="customer__location">Emily, Los Angeles</p>
Имя человека и откуда он вылез сделай h3, будет заголовком артикля

2022-08-07 06:43 UTC, theIvanChornyi commented on src/partials/customer-reviews.html
> +                    <p class="customer__location">Emily, Los Angeles</p>
Имя человека и откуда он вылез сделай h3, будет заголовком артикля

2022-08-07 06:43 UTC, theIvanChornyi commented on src/partials/customer-reviews.html
> +                    <p class="customer__location">Emily, Los Angeles</p>
Имя человека и откуда он вылез сделай h3, будет заголовком артикля

2022-08-07 06:43 UTC, theIvanChornyi commented on src/sass/components/_customer-reviews.scss
> +.swiper-pagination-clickable .swiper-pagination-bullet {
У этого селектора высокая селективность что не даёт тебе перебить стили нижи, напиши просто и дай ему только ширину и высоту .swiper-pagination-bullet {
    width: 12px;
    height: 12px;

2022-08-07 06:43 UTC, theIvanChornyi commented on src/sass/components/_customer-reviews.scss
> +    overflow: visible;
overflow: visible; не поможет, напиши border-radius: 0; и у активного  background-color: transparent;

2022-08-07 06:43 UTC, theIvanChornyi commented on src/sass/components/_customer-reviews.scss
> +    padding: 60px 0px;
Падинг сделай только верхний, тот что снизу сделал уже Андрей

2022-08-07 06:43 UTC, theIvanChornyi commented on src/sass/components/_customer-reviews.scss
> +    margin-bottom: 34px;
У меня по макету     margin-bottom: 32px;

2022-08-07 06:43 UTC, theIvanChornyi commented on src/sass/components/_customer-reviews.scss
> +            @include tablet {
![Screenshot_4](https://user-images.githubusercontent.com/107806721/183278673-204c6155-46d9-4202-9dba-e625a9f58937.png)
В планшетной версии не так как на макете

2022-08-07 07:00 UTC, theIvanChornyi requested changes

2022-08-07 07:00 UTC, theIvanChornyi commented on src/partials/customer-reviews.html
> +<section class="customer">
Сюда дай id="review--ancor"

2022-08-07 08:57 UTC, Kate3587 commented on src/partials/customer-reviews.html
> +    <div class="swiper mySwiper">
+++

2022-08-07 09:04 UTC, Kate3587 commented on src/partials/customer-reviews.html
> +                <div>
+++

2022-08-07 09:04 UTC, Kate3587 commented on src/partials/customer-reviews.html
> +                <div>
+++

2022-08-07 09:04 UTC, Kate3587 commented on src/partials/customer-reviews.html
> +                <div>
++++

2022-08-07 09:06 UTC, Kate3587 commented on src/partials/customer-reviews.html
> +                    <p class="customer__location">Emily, Los Angeles</p>
++++

2022-08-07 09:08 UTC, Kate3587 commented on src/sass/components/_customer-reviews.scss
> +.swiper-pagination-clickable .swiper-pagination-bullet {
++

2022-08-07 09:09 UTC, Kate3587 commented on src/sass/components/_customer-reviews.scss
> +    overflow: visible;
+++

2022-08-07 09:11 UTC, Kate3587 commented on src/sass/components/_customer-reviews.scss
> +    margin-bottom: 34px;
у меня нет

2022-08-07 09:12 UTC, Kate3587 commented on src/partials/customer-reviews.html
> +<section class="customer">
+++

2022-08-07 09:14 UTC, Kate3587 commented on src/sass/components/_customer-reviews.scss
> +    margin-bottom: 34px;
+++

2022-08-07 09:28 UTC, Kate3587 commented on src/sass/components/_customer-reviews.scss
> +            @include tablet {
++++

2022-08-07 11:09 UTC, theIvanChornyi approved these changes

2022-08-07 11:09 UTC, merged