Add products
theIvanChornyi/html-css-project pull request #19
Opened 2022-08-06 17:23 UTC by Kate3587

2022-08-06 18:23 UTC, theIvanChornyi requested changes

2022-08-06 18:23 UTC, theIvanChornyi commented on src/sass/components/_products.scss
> +    width: 38px;
Тут сделай ширину 40

2022-08-06 18:23 UTC, theIvanChornyi commented on src/partials/products.html
> +        <div class="products__card card ">
products__card Это не div а ul

2022-08-06 18:23 UTC, theIvanChornyi commented on src/partials/products.html
> +            <div class="card__item">
Соответственно каждый products__card это li

2022-08-06 18:23 UTC, theIvanChornyi commented on src/partials/products.html
> +            <div class="card__item">
Соответственно каждый products__card это li

2022-08-06 18:23 UTC, theIvanChornyi commented on src/partials/products.html
> +            <div class="card__item">
Соответственно каждый products__card это li

2022-08-06 18:23 UTC, theIvanChornyi commented on src/sass/components/_header.scss
> +  display: none;
Это убери display: none;

2022-08-07 05:54 UTC, theIvanChornyi requested changes

2022-08-07 05:54 UTC, theIvanChornyi commented on src/sass/components/_products.scss
>      padding: 0px 40px 40px;
Тут падинг padding: 160px 40px 40px;

2022-08-07 05:54 UTC, theIvanChornyi commented on src/sass/components/_products.scss
>          padding: 0px 40px 32px;
Сдесб падинг  padding: 118px 40px 32px;

2022-08-07 05:54 UTC, theIvanChornyi commented on src/sass/components/_products.scss
>          padding: 0px 60px 61px;
padding: 165px 60px 61px;

2022-08-07 05:54 UTC, theIvanChornyi commented on src/sass/components/_products.scss
> -    width: 38px;
Сдесь дай кнопке flex-shrink: 0; И она не будет сжиматься

2022-08-07 06:00 UTC, theIvanChornyi requested changes

2022-08-07 06:00 UTC, theIvanChornyi commented on src/sass/components/_products.scss
> +    @include font(null, 16px, null, null, null);
не обязательно к исправлению, но если у тебя миксин выглядит так    @include font(null, 16px, null, null, null);,
то просто давай font-size: 16px; Для тебя писанины меньше просто

2022-08-07 06:58 UTC, theIvanChornyi requested changes

2022-08-07 06:58 UTC, theIvanChornyi commented on src/partials/products.html
> +<section class="products">
Дай секции id="products--ancor" Это чтобы кнопка в хедере проскролливала на твою секцию

2022-08-07 08:39 UTC, Kate3587 commented on src/sass/components/_products.scss
>      padding: 0px 40px 40px;
+++

2022-08-07 08:40 UTC, Kate3587 commented on src/sass/components/_products.scss
>          padding: 0px 40px 32px;
+++

2022-08-07 08:41 UTC, Kate3587 commented on src/sass/components/_products.scss
>          padding: 0px 60px 61px;
+++

2022-08-07 08:41 UTC, Kate3587 commented on src/sass/components/_products.scss
> -    width: 38px;
+++

2022-08-07 08:43 UTC, Kate3587 commented on src/sass/components/_products.scss
> +    @include font(null, 16px, null, null, null);
+++

2022-08-07 08:44 UTC, Kate3587 commented on src/partials/products.html
> +<section class="products">
+++

2022-08-07 10:43 UTC, theIvanChornyi approved these changes

2022-08-07 10:43 UTC, merged